import "server-only";
import { and, count, desc, eq, gt, inArray, isNull, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { generations, posts, traces } from "@/db/schema";

export type CronJob = "discover" | "generate" | "post" | "wave";

export type CronStatus = {
  job: CronJob;
  agent: string;
  vercelSchedule: string;
  vercelScheduleHuman: string;
  lastRunAt: Date | null;
  lastRunOk: boolean | null;
  lastRunPayload: Record<string, unknown> | null;
  runsLast24h: number;
};

const JOB_TO_AGENT: Record<CronJob, string> = {
  discover: "discover",
  generate: "cron-generate",
  post: "cron-post",
  wave: "cron-wave",
};

const JOB_SCHEDULES: Record<CronJob, { cron: string; human: string }> = {
  discover: { cron: "0 */12 * * *", human: "every 12 hours" },
  generate: { cron: "0 */4 * * *", human: "every 4 hours" },
  post: { cron: "*/15 * * * *", human: "every 15 minutes" },
  wave: { cron: "0 10 * * *", human: "daily" },
};

async function loadCronStatus(job: CronJob): Promise<CronStatus> {
  const agent = JOB_TO_AGENT[job];
  const schedule = JOB_SCHEDULES[job];
  const last24 = new Date(Date.now() - 24 * 3600 * 1000);

  // last run = latest complete/skip/error event for this agent
  const [lastRow] = await db
    .select({
      ts: traces.ts,
      eventType: traces.eventType,
      payload: traces.payload,
    })
    .from(traces)
    .where(
      and(
        eq(traces.agent, agent),
        inArray(traces.eventType, [
          "complete",
          "complete_with_errors",
          "skip",
          "error",
        ]),
      ),
    )
    .orderBy(desc(traces.ts))
    .limit(1);

  const [countRow] = await db
    .select({ c: count() })
    .from(traces)
    .where(
      and(
        eq(traces.agent, agent),
        gt(traces.ts, last24),
        inArray(traces.eventType, [
          "complete",
          "complete_with_errors",
          "skip",
        ]),
      ),
    );

  return {
    job,
    agent,
    vercelSchedule: schedule.cron,
    vercelScheduleHuman: schedule.human,
    lastRunAt: lastRow?.ts ?? null,
    lastRunOk: lastRow
      ? lastRow.eventType === "complete" || lastRow.eventType === "skip"
      : null,
    lastRunPayload: (lastRow?.payload as Record<string, unknown> | null) ?? null,
    runsLast24h: countRow?.c ?? 0,
  };
}

export async function loadAllCronStatus(): Promise<CronStatus[]> {
  return Promise.all([
    loadCronStatus("discover"),
    loadCronStatus("generate"),
    loadCronStatus("post"),
    loadCronStatus("wave"),
  ]);
}

export type AutonomyStats = {
  autoGeneratedToday: number;
  autoPostedToday: number;
  topicGuardSafeToday: number;
  topicGuardBlockedToday: number;
};

export async function loadAutonomyStats(): Promise<AutonomyStats> {
  const startOfToday = new Date(
    Date.UTC(
      new Date().getUTCFullYear(),
      new Date().getUTCMonth(),
      new Date().getUTCDate(),
    ),
  );

  const [autoGen, autoPost, guardSafe, guardBlocked] = await Promise.all([
    db
      .select({ c: count() })
      .from(generations)
      .where(
        and(
          gt(generations.createdAt, startOfToday),
          sql`${generations.inputMeta} ->> 'source' = 'cron'`,
        ),
      ),
    db
      .select({ c: count() })
      .from(posts)
      .where(
        and(
          gt(posts.postedAt, startOfToday),
          eq(posts.status, "posted"),
          isNull(posts.parentPostId),
        ),
      ),
    db
      .select({ c: count() })
      .from(traces)
      .where(
        and(
          gt(traces.ts, startOfToday),
          eq(traces.agent, "topic-guard"),
          eq(traces.eventType, "safe"),
        ),
      ),
    db
      .select({ c: count() })
      .from(traces)
      .where(
        and(
          gt(traces.ts, startOfToday),
          eq(traces.agent, "topic-guard"),
          eq(traces.eventType, "blocked"),
        ),
      ),
  ]);

  return {
    autoGeneratedToday: autoGen[0]?.c ?? 0,
    autoPostedToday: autoPost[0]?.c ?? 0,
    topicGuardSafeToday: guardSafe[0]?.c ?? 0,
    topicGuardBlockedToday: guardBlocked[0]?.c ?? 0,
  };
}
