"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { TriggerButton } from "./trigger-button";

type WaveShot = {
  topic: string;
  hook: string;
  rationale: string;
  texts: string[];
};

type Stats = {
  autoGeneratedToday: number;
  autoPostedToday: number;
  topicGuardSafeToday: number;
  topicGuardBlockedToday: number;
};

type CronJob = {
  job: string;
  vercelScheduleHuman: string;
  lastRunAt: string | null;
  lastRunOk: boolean | null;
  runsLast24h: number;
  lastRunPayload: Record<string, unknown> | null;
};

function fmtMoney(usd: number): string {
  if (usd < 0.01) return "<$0.01";
  if (usd < 1) return `${Math.round(usd * 100)}¢`;
  return `$${usd.toFixed(2)}`;
}

function relativeAge(d: string | null): string {
  if (!d) return "never";
  const s = Math.floor((Date.now() - new Date(d).getTime()) / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export function AutomationPanel({
  stats,
  jobs,
  todaySpend,
  cap,
  waveAutonomous,
}: {
  stats: Stats;
  jobs: CronJob[];
  todaySpend: number;
  cap: number;
  waveAutonomous: boolean;
}) {
  const [open, setOpen] = useState(false);
  const capPct = Math.min(100, Math.round((todaySpend / cap) * 100));
  const capColor =
    capPct < 50
      ? "bg-emerald-500"
      : capPct < 80
        ? "bg-amber-500"
        : "bg-destructive";

  return (
    <div className="rounded-lg border bg-card">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between px-4 py-3 text-left"
      >
        <div className="flex items-center gap-4 font-mono text-xs">
          <span className="text-sm font-medium text-foreground">Automation</span>
          <span className="text-muted-foreground">
            {fmtMoney(todaySpend)} / {fmtMoney(cap)}
          </span>
          <div className="h-1.5 w-16 overflow-hidden rounded-full bg-muted">
            <div
              className={`h-full ${capColor} transition-all`}
              style={{ width: `${capPct}%` }}
            />
          </div>
          <span className="text-muted-foreground">
            {stats.autoGeneratedToday} gen · {stats.autoPostedToday} posted
          </span>
        </div>
        <span className="text-xs text-muted-foreground">{open ? "▲" : "▼"}</span>
      </button>

      {open && (
        <div className="flex flex-col gap-4 border-t px-4 py-3">
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 font-mono text-xs md:grid-cols-4">
            <Stat label="auto-generated" value={stats.autoGeneratedToday} />
            <Stat label="posted" value={stats.autoPostedToday} />
            <Stat label="guard safe" value={stats.topicGuardSafeToday} />
            <Stat label="guard blocked" value={stats.topicGuardBlockedToday} />
          </dl>

          {capPct >= 100 && (
            <p className="font-mono text-xs text-destructive">
              Spend cap reached — cron returns 429 until UTC midnight.
            </p>
          )}

          <WaveShotSection autonomous={waveAutonomous} />

          <div className="flex flex-col gap-2">
            <h3 className="font-mono text-xs font-medium text-muted-foreground">
              Cron jobs
            </h3>
            {jobs.map((job) => {
              const endpoint = `/api/cron/${job.job}`;
              return (
                <div
                  key={job.job}
                  className="flex flex-wrap items-center gap-3 rounded-md border bg-muted/20 px-3 py-2 font-mono text-xs"
                >
                  <span className="font-semibold">{job.job}</span>
                  <Badge variant="outline" className="font-mono">
                    {job.vercelScheduleHuman}
                  </Badge>
                  <span className="text-muted-foreground">
                    {relativeAge(job.lastRunAt)}
                  </span>
                  {job.lastRunOk !== null && (
                    <Badge
                      variant={job.lastRunOk ? "outline" : "destructive"}
                      className={`font-mono ${job.lastRunOk ? "text-emerald-700 dark:text-emerald-400" : ""}`}
                    >
                      {job.lastRunOk ? "ok" : "failed"}
                    </Badge>
                  )}
                  <div className="ml-auto">
                    <TriggerButton endpoint={endpoint} label="trigger" />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="text-base font-semibold">{value}</dd>
    </div>
  );
}

// Second automation method: recommend topics from the current viral wave and
// preview a writer-only draft for each (the cron version of this is the "wave"
// job above). Promoting a preview queues it as a draft.
function WaveShotSection({ autonomous }: { autonomous: boolean }) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [shots, setShots] = useState<WaveShot[] | null>(null);
  const [queued, setQueued] = useState<Record<number, "queuing" | "done">>({});
  const [auto, setAuto] = useState(autonomous);
  const [savingAuto, setSavingAuto] = useState(false);

  async function toggleAuto() {
    const next = !auto;
    setSavingAuto(true);
    setError(null);
    try {
      const res = await fetch("/api/settings/automation", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ waveAutonomous: next }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setAuto(next);
      router.refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "failed to update autonomy");
    } finally {
      setSavingAuto(false);
    }
  }

  async function runShot() {
    setLoading(true);
    setError(null);
    setShots(null);
    setQueued({});
    try {
      const res = await fetch("/api/wave/shot", { method: "POST" });
      const data = (await res.json().catch(() => ({}))) as {
        shots?: WaveShot[];
        message?: string;
        error?: string;
      };
      if (!res.ok) {
        setError(data.message ?? data.error ?? `HTTP ${res.status}`);
        return;
      }
      setShots(data.shots ?? []);
    } catch (e) {
      setError(e instanceof Error ? e.message : "failed to run wave shot");
    } finally {
      setLoading(false);
    }
  }

  async function queueShot(i: number, shot: WaveShot) {
    setQueued((q) => ({ ...q, [i]: "queuing" }));
    try {
      const res = await fetch("/api/wave/queue", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: shot.topic,
          text: shot.texts[0] ?? "",
          hook: shot.hook,
        }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setQueued((q) => ({ ...q, [i]: "done" }));
      router.refresh();
    } catch (e) {
      setQueued((q) => {
        const next = { ...q };
        delete next[i];
        return next;
      });
      setError(e instanceof Error ? e.message : "failed to queue");
    }
  }

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-3">
        <h3 className="font-mono text-xs font-medium text-muted-foreground">
          Viral wave shot
        </h3>
        <span className="font-mono text-[10px] text-muted-foreground">
          recommend topics from the wave + preview drafts
        </span>
        <button
          onClick={toggleAuto}
          disabled={savingAuto}
          title={
            auto
              ? "Full-autonomous ON: the daily wave cron auto-generates AND auto-posts to X with no review. Click to disable."
              : "Enable full-autonomous: the daily wave cron will auto-generate AND auto-post to X unattended."
          }
          className={`ml-auto rounded px-2 py-0.5 font-mono text-[10px] transition-colors disabled:opacity-50 ${
            auto
              ? "bg-destructive text-white"
              : "bg-muted text-muted-foreground hover:bg-muted/70"
          }`}
        >
          {savingAuto ? "…" : auto ? "● full-auto ON" : "full-auto OFF"}
        </button>
        <Button
          variant="outline"
          size="sm"
          className="font-mono"
          onClick={runShot}
          disabled={loading}
        >
          {loading ? "shooting…" : "viral wave shot"}
        </Button>
      </div>
      {auto ? (
        <p className="font-mono text-[10px] text-destructive">
          ⚠ full-autonomous is ON — the daily wave will post to X without review.
        </p>
      ) : null}

      {error ? (
        <p className="font-mono text-xs text-destructive">{error}</p>
      ) : null}

      {shots && shots.length === 0 && !loading ? (
        <p className="font-mono text-xs text-muted-foreground">
          No topics — fetch viral posts first, then try again.
        </p>
      ) : null}

      {shots?.map((shot, i) => (
        <div
          key={i}
          className="flex flex-col gap-1 rounded-md border bg-muted/20 p-3"
        >
          <div className="flex flex-wrap items-baseline gap-2">
            <span className="font-mono text-xs font-semibold">{shot.topic}</span>
            {shot.rationale ? (
              <span className="font-mono text-[10px] text-muted-foreground">
                {shot.rationale}
              </span>
            ) : null}
          </div>
          {shot.texts.map((t, ti) => (
            <p key={ti} className="whitespace-pre-wrap text-sm leading-relaxed">
              {t}
            </p>
          ))}
          <div className="flex items-center gap-2">
            <span className="font-mono text-[10px] text-muted-foreground">
              {shot.texts[0]?.length ?? 0} chars
            </span>
            <Button
              variant="outline"
              size="sm"
              className="ml-auto font-mono"
              onClick={() => queueShot(i, shot)}
              disabled={queued[i] === "queuing" || queued[i] === "done"}
            >
              {queued[i] === "done"
                ? "queued ✓"
                : queued[i] === "queuing"
                  ? "queuing…"
                  : "queue this"}
            </Button>
          </div>
        </div>
      ))}
    </div>
  );
}
