"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { TriggerButton } from "./trigger-button";

type Stats = {
  autoGeneratedToday: number;
  autoPostedToday: number;
  topicGuardSafeToday: number;
  topicGuardBlockedToday: number;
};

type CronJob = {
  job: string;
  vercelScheduleHuman: string;
  lastRunAt: string | null;
  lastRunOk: boolean | null;
  runsLast24h: number;
  lastRunPayload: Record<string, unknown> | null;
};

function fmtMoney(usd: number): string {
  if (usd < 0.01) return "<$0.01";
  if (usd < 1) return `${Math.round(usd * 100)}¢`;
  return `$${usd.toFixed(2)}`;
}

function relativeAge(d: string | null): string {
  if (!d) return "never";
  const s = Math.floor((Date.now() - new Date(d).getTime()) / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export function AutomationPanel({
  stats,
  jobs,
  todaySpend,
  cap,
}: {
  stats: Stats;
  jobs: CronJob[];
  todaySpend: number;
  cap: number;
}) {
  const [open, setOpen] = useState(false);
  const capPct = Math.min(100, Math.round((todaySpend / cap) * 100));
  const capColor =
    capPct < 50
      ? "bg-emerald-500"
      : capPct < 80
        ? "bg-amber-500"
        : "bg-destructive";

  return (
    <div className="rounded-lg border bg-card">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between px-4 py-3 text-left"
      >
        <div className="flex items-center gap-4 font-mono text-xs">
          <span className="text-sm font-medium text-foreground">Automation</span>
          <span className="text-muted-foreground">
            {fmtMoney(todaySpend)} / {fmtMoney(cap)}
          </span>
          <div className="h-1.5 w-16 overflow-hidden rounded-full bg-muted">
            <div
              className={`h-full ${capColor} transition-all`}
              style={{ width: `${capPct}%` }}
            />
          </div>
          <span className="text-muted-foreground">
            {stats.autoGeneratedToday} gen · {stats.autoPostedToday} posted
          </span>
        </div>
        <span className="text-xs text-muted-foreground">{open ? "▲" : "▼"}</span>
      </button>

      {open && (
        <div className="flex flex-col gap-4 border-t px-4 py-3">
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 font-mono text-xs md:grid-cols-4">
            <Stat label="auto-generated" value={stats.autoGeneratedToday} />
            <Stat label="posted" value={stats.autoPostedToday} />
            <Stat label="guard safe" value={stats.topicGuardSafeToday} />
            <Stat label="guard blocked" value={stats.topicGuardBlockedToday} />
          </dl>

          {capPct >= 100 && (
            <p className="font-mono text-xs text-destructive">
              Spend cap reached — cron returns 429 until UTC midnight.
            </p>
          )}

          <div className="flex flex-col gap-2">
            <h3 className="font-mono text-xs font-medium text-muted-foreground">
              Cron jobs
            </h3>
            {jobs.map((job) => {
              const endpoint = `/api/cron/${job.job}`;
              return (
                <div
                  key={job.job}
                  className="flex flex-wrap items-center gap-3 rounded-md border bg-muted/20 px-3 py-2 font-mono text-xs"
                >
                  <span className="font-semibold">{job.job}</span>
                  <Badge variant="outline" className="font-mono">
                    {job.vercelScheduleHuman}
                  </Badge>
                  <span className="text-muted-foreground">
                    {relativeAge(job.lastRunAt)}
                  </span>
                  {job.lastRunOk !== null && (
                    <Badge
                      variant={job.lastRunOk ? "outline" : "destructive"}
                      className={`font-mono ${job.lastRunOk ? "text-emerald-700 dark:text-emerald-400" : ""}`}
                    >
                      {job.lastRunOk ? "ok" : "failed"}
                    </Badge>
                  )}
                  <div className="ml-auto">
                    <TriggerButton endpoint={endpoint} label="trigger" />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="text-base font-semibold">{value}</dd>
    </div>
  );
}
