import { z } from "zod";
import { db } from "@/db/client";
import { sources } from "@/db/schema";
import { requireUser } from "@/lib/auth";
import {
  parseUpload,
  UPLOAD_MAX_BYTES,
  UPLOAD_ALLOWED_MIME_TYPES,
} from "@/lib/parse-upload";

// OpenAI file/vision parse can take a while — pin the budget so the platform
// doesn't kill the request mid-parse (the default would stall the upload).
export const maxDuration = 120;

// ─── JSON text path (existing) ───────────────────────────────────────────────

const JsonUploadRequest = z.object({
  title: z.string().min(1).max(500),
  content: z.string().min(1).max(50_000),
  url: z.string().url().optional(),
  type: z.enum(["manual", "web"]).default("manual"),
});

// ─── Multipart file path ─────────────────────────────────────────────────────

const MultipartMetaRequest = z.object({
  /** Optional caller-supplied title; generated by OpenAI if omitted. */
  title: z.string().min(1).max(500).optional(),
});

// ─── Handlers ────────────────────────────────────────────────────────────────

export async function POST(request: Request) {
  const user = await requireUser();
  const contentType = request.headers.get("content-type") ?? "";

  // ── Multipart / file upload path ──────────────────────────────────────────
  if (contentType.startsWith("multipart/form-data")) {
    let formData: FormData;
    try {
      formData = await request.formData();
    } catch {
      return Response.json({ error: "failed to parse multipart body" }, { status: 400 });
    }

    const fileField = formData.get("file");
    if (!(fileField instanceof File)) {
      return Response.json(
        { error: "missing required field: file (must be a File/Blob)" },
        { status: 400 },
      );
    }

    // Validate optional meta fields
    const metaRaw: Record<string, unknown> = {};
    const titleField = formData.get("title");
    if (titleField !== null) metaRaw.title = titleField;

    const metaParsed = MultipartMetaRequest.safeParse(metaRaw);
    if (!metaParsed.success) {
      return Response.json(
        { error: "invalid form fields", details: metaParsed.error.flatten() },
        { status: 400 },
      );
    }

    const bytes = new Uint8Array(await fileField.arrayBuffer());
    const mimeType = fileField.type || "application/octet-stream";
    const filename = fileField.name || "upload";

    // Validate before calling OpenAI
    if (bytes.length > UPLOAD_MAX_BYTES) {
      return Response.json(
        {
          error: `File too large: ${bytes.length} bytes. Maximum is ${UPLOAD_MAX_BYTES} bytes (10 MB).`,
        },
        { status: 400 },
      );
    }

    if (!(UPLOAD_ALLOWED_MIME_TYPES as ReadonlyArray<string>).includes(mimeType)) {
      return Response.json(
        {
          error: `Unsupported file type: ${mimeType}. Allowed: ${UPLOAD_ALLOWED_MIME_TYPES.join(", ")}`,
        },
        { status: 400 },
      );
    }

    let parsed: Awaited<ReturnType<typeof parseUpload>>;
    try {
      parsed = await parseUpload({ bytes, mimeType, filename });
    } catch (err) {
      const e = err as Error & { status?: number };
      const status = e.status === 400 ? 400 : 502;
      return Response.json(
        { error: e.message ?? "failed to parse uploaded file" },
        { status },
      );
    }

    const title = metaParsed.data.title ?? parsed.title;
    // Scope to the user: the (type, externalId) unique index is global, so a
    // content-derived key without the user id lets one user's upload overwrite
    // another's identically-named, same-size file.
    const externalId = `upload-${user.id}-${filename}-${bytes.length}`;

    const [row] = await db
      .insert(sources)
      .values({
        userId: user.id,
        type: parsed.kind,
        externalId,
        url: null,
        title,
        content: parsed.text,
        meta: {
          filename,
          bytes: bytes.length,
          mimeType,
          tokensIn: parsed.tokensIn,
          tokensOut: parsed.tokensOut,
          costUsd: parsed.costUsd,
        },
      })
      .onConflictDoUpdate({
        target: [sources.type, sources.externalId],
        set: {
          title,
          content: parsed.text,
          meta: {
            filename,
            bytes: bytes.length,
            mimeType,
            tokensIn: parsed.tokensIn,
            tokensOut: parsed.tokensOut,
            costUsd: parsed.costUsd,
          },
        },
      })
      .returning();

    return Response.json(
      {
        source: row,
        parse: {
          kind: parsed.kind,
          tokensIn: parsed.tokensIn,
          tokensOut: parsed.tokensOut,
          costUsd: parsed.costUsd,
        },
      },
      { status: 201 },
    );
  }

  // ── JSON text path (existing) ──────────────────────────────────────────────
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "invalid json" }, { status: 400 });
  }

  const jsonParsed = JsonUploadRequest.safeParse(body);
  if (!jsonParsed.success) {
    return Response.json(
      { error: "invalid payload", details: jsonParsed.error.flatten() },
      { status: 400 },
    );
  }

  const { title, content, url, type } = jsonParsed.data;
  const externalId = url ?? `manual-${Date.now()}`;

  const [row] = await db
    .insert(sources)
    .values({
      userId: user.id,
      type,
      externalId,
      url: url ?? null,
      title,
      content,
    })
    .onConflictDoUpdate({
      target: [sources.type, sources.externalId],
      set: { title, content },
    })
    .returning();

  return Response.json(
    { source: row },
    { status: 201 },
  );
}

export async function GET() {
  const user = await requireUser();
  const { eq } = await import("drizzle-orm");
  const rows = await db
    .select({
      id: sources.id,
      type: sources.type,
      title: sources.title,
      url: sources.url,
      ingestedAt: sources.ingestedAt,
    })
    .from(sources)
    .where(eq(sources.userId, user.id))
    .orderBy(sources.ingestedAt)
    .limit(50);

  return Response.json({ sources: rows });
}
