import { count, eq, isNull, sql } from "drizzle-orm";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { db } from "@/db/client";
import { generations, posts, type PostStatus } from "@/db/schema";
import { loadAllCronStatus, loadAutonomyStats } from "@/lib/automation";
import { loadBilling } from "@/lib/billing";
import { env } from "@/lib/env";

export const dynamic = "force-dynamic";

type QueueCounts = Record<PostStatus, number>;

async function loadQueueCounts(): Promise<QueueCounts> {
  const init: QueueCounts = {
    draft: 0,
    approved: 0,
    scheduled: 0,
    posted: 0,
    failed: 0,
    skipped: 0,
  };
  try {
    const rows = await db
      .select({ status: posts.status, n: sql<number>`count(*)::int` })
      .from(posts)
      .where(isNull(posts.parentPostId))
      .groupBy(posts.status);
    for (const r of rows) init[r.status] = r.n;
  } catch {}
  return init;
}

async function lastShipped(): Promise<{ at: Date; text: string } | null> {
  try {
    const [row] = await db
      .select({ postedAt: posts.postedAt, text: posts.text })
      .from(posts)
      .where(eq(posts.status, "posted"))
      .orderBy(sql`${posts.postedAt} DESC NULLS LAST`)
      .limit(1);
    if (!row?.postedAt) return null;
    return { at: row.postedAt, text: row.text };
  } catch {
    return null;
  }
}

async function genCountToday(): Promise<number> {
  try {
    const today = new Date(
      Date.UTC(
        new Date().getUTCFullYear(),
        new Date().getUTCMonth(),
        new Date().getUTCDate(),
      ),
    );
    const [r] = await db
      .select({ c: count() })
      .from(generations)
      .where(sql`${generations.createdAt} >= ${today}`);
    return r?.c ?? 0;
  } catch {
    return 0;
  }
}

function ago(d: Date): string {
  const sec = Math.floor((Date.now() - d.getTime()) / 1000);
  if (sec < 60) return `${sec}s ago`;
  if (sec < 3600) return `${Math.floor(sec / 60)}m ago`;
  if (sec < 86400) return `${Math.floor(sec / 3600)}h ago`;
  return `${Math.floor(sec / 86400)}d ago`;
}

export default async function HomePage() {
  const [counts, billing, crons, autonomy, lastPost, genToday] =
    await Promise.all([
      loadQueueCounts(),
      loadBilling(),
      loadAllCronStatus(),
      loadAutonomyStats(),
      lastShipped(),
      genCountToday(),
    ]);

  const todayUsd = billing?.today.totalUsd ?? 0;
  const capUsd = env.MAX_DAILY_USD;
  const capPct = Math.min(100, Math.round((todayUsd / capUsd) * 100));
  const capBarColor =
    capPct >= 90
      ? "bg-destructive"
      : capPct >= 70
        ? "bg-amber-500"
        : "bg-emerald-500";

  const actionable = counts.draft + counts.approved + counts.scheduled;
  const postCron = crons.find((c) => c.job === "post");
  const generateCron = crons.find((c) => c.job === "generate");

  return (
    <div className="flex flex-col gap-8 p-8">
      <header className="flex items-baseline justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Dashboard</h1>
          <p className="text-sm text-muted-foreground">
            {actionable === 0
              ? "Queue's empty. Compose something or wait for autonomous to fire."
              : `${counts.draft} draft${counts.draft === 1 ? "" : "s"} waiting · ${counts.approved + counts.scheduled} approved`}
          </p>
        </div>
        <div className="flex items-center gap-3 text-xs font-mono text-muted-foreground">
          <span>${todayUsd.toFixed(3)} / ${capUsd.toFixed(2)} today</span>
          <Badge variant={capPct >= 90 ? "destructive" : "outline"}>
            cap {capPct}%
          </Badge>
        </div>
      </header>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
        <Tile
          label="Queue actionable"
          value={String(actionable)}
          hint={`${counts.draft} draft · ${counts.approved} approved · ${counts.scheduled} sched`}
          href="/queue"
          accent={actionable > 0 ? "blue" : "muted"}
        />
        <Tile
          label="Posted today"
          value={String(autonomy.autoPostedToday + counts.posted >= autonomy.autoPostedToday ? counts.posted : autonomy.autoPostedToday)}
          hint={
            lastPost
              ? `last: ${ago(lastPost.at)}`
              : "no posts yet"
          }
          href="/queue?filter=posted"
          accent="emerald"
        />
        <Tile
          label="Spend today"
          value={`$${todayUsd.toFixed(3)}`}
          hint={`${genToday} generation${genToday === 1 ? "" : "s"} · cap ${capPct}%`}
          href="/automation"
          accent={capPct >= 90 ? "amber" : "muted"}
          bar={{ pct: capPct, color: capBarColor }}
        />
        <Tile
          label="Autonomous today"
          value={`${autonomy.autoGeneratedToday} gen / ${autonomy.autoPostedToday} ship`}
          hint={`safe ${autonomy.topicGuardSafeToday} · blocked ${autonomy.topicGuardBlockedToday}`}
          href="/automation"
          accent="muted"
        />
      </section>

      <section className="flex flex-wrap items-center gap-3">
        <Link href="/compose">
          <Button>+ New draft</Button>
        </Link>
        <Link href="/queue">
          <Button variant="outline">Open queue</Button>
        </Link>
        <Link href="/discover">
          <Button variant="outline">Discover viral</Button>
        </Link>
        <Link href="/automation">
          <Button variant="ghost" className="text-muted-foreground">
            Automation control
          </Button>
        </Link>
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-2">
        <Card title="Last shipped post">
          {lastPost ? (
            <div className="flex flex-col gap-1">
              <p className="text-sm leading-snug">
                {lastPost.text.length > 200
                  ? lastPost.text.slice(0, 200) + "…"
                  : lastPost.text}
              </p>
              <p className="text-xs text-muted-foreground">
                {ago(lastPost.at)} · {lastPost.at.toISOString().slice(0, 16)}Z
              </p>
            </div>
          ) : (
            <EmptyHint>
              No posts yet. Compose a draft and ship it — Telegram approval
              works from your phone.
            </EmptyHint>
          )}
        </Card>
        <Card title="Cron health">
          <ul className="flex flex-col gap-2 text-xs">
            {crons.map((c) => (
              <li
                key={c.job}
                className="flex items-baseline justify-between gap-3"
              >
                <span className="font-mono">{c.job}</span>
                <span className="text-muted-foreground">
                  {c.vercelScheduleHuman} ·{" "}
                  {c.lastRunAt
                    ? `last ${ago(c.lastRunAt)} ${c.lastRunOk ? "✓" : "✗"}`
                    : "never"}
                </span>
              </li>
            ))}
            {postCron && generateCron && (
              <li className="mt-1 border-t pt-2 text-muted-foreground">
                next post check ≤ 15m · next gen tick ≤ 4h
              </li>
            )}
          </ul>
        </Card>
      </section>
    </div>
  );
}

function Tile({
  label,
  value,
  hint,
  href,
  accent,
  bar,
}: {
  label: string;
  value: string;
  hint: string;
  href: string;
  accent: "blue" | "emerald" | "amber" | "muted";
  bar?: { pct: number; color: string };
}) {
  const accentBg = {
    blue: "border-blue-500/30 bg-blue-500/5",
    emerald: "border-emerald-500/30 bg-emerald-500/5",
    amber: "border-amber-500/30 bg-amber-500/5",
    muted: "",
  }[accent];

  return (
    <Link
      href={href}
      className={`group flex flex-col gap-1 rounded-lg border p-4 transition-colors hover:bg-muted/50 ${accentBg}`}
    >
      <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
        {label}
      </span>
      <span className="text-2xl font-semibold tracking-tight tabular-nums">
        {value}
      </span>
      <span className="font-mono text-[11px] text-muted-foreground">
        {hint}
      </span>
      {bar ? (
        <div className="mt-1 h-1 w-full overflow-hidden rounded bg-muted">
          <div
            className={`h-full transition-all ${bar.color}`}
            style={{ width: `${bar.pct}%` }}
          />
        </div>
      ) : null}
    </Link>
  );
}

function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border p-4">
      <h2 className="mb-3 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
        {title}
      </h2>
      {children}
    </div>
  );
}

function EmptyHint({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-xs text-muted-foreground italic">{children}</p>
  );
}
