import { AutoRefresh } from "@/components/shell/auto-refresh";
import { Badge } from "@/components/ui/badge";
import { env } from "@/lib/env";
import {
  loadAllCronStatus,
  loadAutonomyStats,
  type CronStatus,
} from "@/lib/automation";
import { loadBilling } from "@/lib/billing";
import { TriggerButton } from "./trigger-button";

export const dynamic = "force-dynamic";

function relativeAge(d: Date | string | null): string {
  if (!d) return "never";
  const ts = typeof d === "string" ? new Date(d).getTime() : d.getTime();
  const s = Math.floor((Date.now() - ts) / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function fmtMoney(usd: number): string {
  if (usd < 0.01) return "<$0.01";
  if (usd < 1) return `${Math.round(usd * 100)}¢`;
  return `$${usd.toFixed(2)}`;
}

export default async function AutomationPage() {
  const [jobs, stats, billing] = await Promise.all([
    loadAllCronStatus(),
    loadAutonomyStats(),
    loadBilling(),
  ]);

  const todaySpend = billing?.today.totalUsd ?? 0;
  const cap = env.MAX_DAILY_USD;
  const capPct = Math.min(100, Math.round((todaySpend / cap) * 100));
  const capColor =
    capPct < 50
      ? "bg-emerald-500"
      : capPct < 80
        ? "bg-amber-500"
        : "bg-destructive";

  return (
    <div className="flex flex-col gap-6 p-8">
      <header className="flex items-baseline justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Automation</h1>
          <p className="text-sm text-muted-foreground">
            Autonomous loop status. Local dev: use trigger buttons or{" "}
            <code className="font-mono">npm run cron:local</code>. Production:
            Vercel Cron runs on schedule.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <AutoRefresh intervalMs={20_000} label="live" />
          <Badge variant="outline" className="font-mono">
            slice 17
          </Badge>
        </div>
      </header>

      <section className="flex flex-col gap-3 rounded-lg border bg-card p-4">
        <h2 className="text-sm font-medium">Today&apos;s autonomy</h2>
        <dl className="grid grid-cols-2 gap-x-6 gap-y-2 font-mono text-xs md:grid-cols-4">
          <Stat label="auto-generated" value={stats.autoGeneratedToday} />
          <Stat label="posted" value={stats.autoPostedToday} />
          <Stat label="topic-guard safe" value={stats.topicGuardSafeToday} />
          <Stat label="topic-guard blocked" value={stats.topicGuardBlockedToday} />
        </dl>

        <div className="mt-2 flex flex-col gap-1.5">
          <div className="flex items-center justify-between font-mono text-xs text-muted-foreground">
            <span>daily spend cap</span>
            <span>
              <span className="font-semibold text-foreground">
                {fmtMoney(todaySpend)}
              </span>{" "}
              / {fmtMoney(cap)} ({capPct}%)
            </span>
          </div>
          <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
            <div
              className={`h-full ${capColor} transition-all`}
              style={{ width: `${capPct}%` }}
            />
          </div>
          {capPct >= 100 ? (
            <p className="font-mono text-xs text-destructive">
              ⛔ cron endpoints will return 429 until UTC midnight
            </p>
          ) : null}
        </div>
      </section>

      <section className="flex flex-col gap-3 rounded-lg border bg-card p-4">
        <h2 className="text-sm font-medium">Cron jobs</h2>
        <div className="flex flex-col gap-3">
          {jobs.map((job) => (
            <CronJobRow key={job.job} job={job} />
          ))}
        </div>
      </section>

      <p className="font-mono text-xs text-muted-foreground">
        Triggers below fire the same endpoints Vercel Cron will hit in
        production — useful for local smoke tests. Each respects the spend cap
        and Bearer auth.
      </p>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="text-base font-semibold">{value}</dd>
    </div>
  );
}

function CronJobRow({ job }: { job: CronStatus }) {
  const endpoint = `/api/cron/${job.job}`;
  const okBadge =
    job.lastRunOk === null
      ? null
      : job.lastRunOk
        ? (
          <Badge
            variant="outline"
            className="font-mono text-emerald-700 dark:text-emerald-400"
          >
            ok
          </Badge>
        )
        : (
          <Badge variant="destructive" className="font-mono">
            failed
          </Badge>
        );

  return (
    <div className="flex flex-col gap-2 rounded-md border bg-muted/20 p-3">
      <div className="flex flex-wrap items-center gap-3 font-mono text-xs">
        <span className="font-semibold text-foreground">{endpoint}</span>
        <Badge variant="outline" className="font-mono">
          {job.vercelScheduleHuman}
        </Badge>
        <span className="text-muted-foreground">
          last run: {relativeAge(job.lastRunAt)}
        </span>
        {okBadge}
        <span className="ml-auto text-muted-foreground">
          {job.runsLast24h} run{job.runsLast24h === 1 ? "" : "s"} last 24h
        </span>
      </div>

      <TriggerButton endpoint={endpoint} label={`trigger ${job.job} now`} />

      {job.lastRunPayload && Object.keys(job.lastRunPayload).length > 0 ? (
        <details className="font-mono text-xs text-muted-foreground">
          <summary className="cursor-pointer">last payload</summary>
          <pre className="mt-2 max-w-3xl overflow-x-auto rounded-md bg-muted px-2 py-1">
            {JSON.stringify(job.lastRunPayload, null, 2)}
          </pre>
        </details>
      ) : null}
    </div>
  );
}
